#!/usr/bin/env python3
"""Install this repository's doctrine at user scope, so it reaches every session.

The owner's most-repeated request is that the rules apply to "all my prompts in
all my chats and all my terminals" - four separate goals say so
(profile/OWNER-PROFILE.md, P4). A file committed here does not do that. Project
files govern work in this repository and nowhere else, so committing one and
calling the request delivered is the kind of overclaim this repository exists to
prevent.

This script closes the gap it actually can close, and is explicit about the part
it cannot.

WHAT IT REACHES
  Claude Code sessions on this machine, in any directory, via ~/.claude/.
  That covers the "all my terminals" half of the request.

WHAT IT DOES NOT REACH
  claude.ai web conversations. Those do not read ~/.claude/, and nothing on this
  filesystem can change them. The equivalent there is pasting prompts/base-operator.md
  into a Project's custom instructions, which is a manual step this script cannot
  perform. Anyone reporting this script as having covered "all my chats" is
  wrong, and the script says so in its own output.

HOW IT WRITES
  Everything goes inside a marked block, so re-running replaces this repository's
  content and never touches anything the owner wrote by hand. Files that are not
  ours are copied only if absent, or with a .bak alongside when --force is given.

Usage
  python3 tools/install_user_scope.py              # dry run: print the plan
  python3 tools/install_user_scope.py --apply      # write it
  python3 tools/install_user_scope.py --apply --force   # overwrite ours, back up theirs
  python3 tools/install_user_scope.py --uninstall --apply
Exit
  0 clean · 1 nothing to do or partial · 2 could not run
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HOME_CLAUDE = Path.home() / ".claude"

BEGIN = "<!-- BEGIN managed by turkertekten-ship-it/claude -->"
END = "<!-- END managed by turkertekten-ship-it/claude -->"

#: Files copied wholesale into ~/.claude/. Source is relative to the repo root.
COPY: list[tuple[str, str]] = [
    (".claude/skills/ooda/SKILL.md", "skills/ooda/SKILL.md"),
    (".claude/agents/observer.md", "agents/observer.md"),
    (".claude/agents/fact-checker.md", "agents/fact-checker.md"),
    (".claude/commands/observe.md", "commands/observe.md"),
    (".claude/commands/ooda-loop.md", "commands/ooda-loop.md"),
    (".claude/commands/fact-check.md", "commands/fact-check.md"),
    (".claude/commands/source.md", "commands/source.md"),
    (".claude/commands/ultrareview.md", "commands/ultrareview.md"),
]


def managed_block() -> str:
    """The doctrine, rendered for a user-scope CLAUDE.md.

    Deliberately a condensed pointer rather than a copy of the whole prompt:
    user-scope CLAUDE.md loads on every session in every directory, so every
    line in it is paid for on every future turn.
    """
    prompt = (REPO / "prompts" / "base-operator.md").read_text(encoding="utf-8")
    # Drop the title line; it becomes a section here.
    body = prompt.split("\n", 1)[1].strip()
    return (
        f"{BEGIN}\n"
        f"<!-- Generated by tools/install_user_scope.py. Edits inside this block\n"
        f"     are overwritten on the next run. Write your own rules outside it. -->\n\n"
        f"# Operating doctrine\n\n"
        f"{body}\n\n"
        f"> Source of truth: `turkertekten-ship-it/claude`. This block is a copy;\n"
        f"> change the repository, then re-run `tools/install_user_scope.py --apply`.\n"
        f"{END}\n"
    )


def splice(existing: str, block: str) -> str:
    """Replace our block if present, otherwise append it, leaving the rest alone."""
    if BEGIN in existing and END in existing:
        head = existing.split(BEGIN, 1)[0]
        tail = existing.split(END, 1)[1]
        return head.rstrip() + ("\n\n" if head.strip() else "") + block + tail.lstrip("\n")
    if not existing.strip():
        return block
    return existing.rstrip() + "\n\n" + block


def strip_block(existing: str) -> str:
    if BEGIN not in existing or END not in existing:
        return existing
    head = existing.split(BEGIN, 1)[0]
    tail = existing.split(END, 1)[1]
    return (head.rstrip() + "\n" + tail.lstrip("\n")).strip() + "\n"


def plan_copies(force: bool) -> list[tuple[Path, Path, str]]:
    actions: list[tuple[Path, Path, str]] = []
    for src_rel, dst_rel in COPY:
        src = REPO / src_rel
        dst = HOME_CLAUDE / dst_rel
        if not src.exists():
            actions.append((src, dst, "skip: source missing"))
        elif not dst.exists():
            actions.append((src, dst, "create"))
        elif dst.read_text(encoding="utf-8", errors="replace") == src.read_text(
            encoding="utf-8", errors="replace"
        ):
            actions.append((src, dst, "unchanged"))
        elif force:
            actions.append((src, dst, "overwrite (backing up to .bak)"))
        else:
            actions.append((src, dst, "differs: left alone, pass --force to overwrite"))
    return actions


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--apply", action="store_true", help="actually write (default: dry run)")
    ap.add_argument("--force", action="store_true", help="overwrite differing files, keeping .bak")
    ap.add_argument("--uninstall", action="store_true", help="remove the managed block")
    args = ap.parse_args(argv)

    prompt_path = REPO / "prompts" / "base-operator.md"
    if not prompt_path.exists():
        print(f"install: {prompt_path} is missing; nothing to install", file=sys.stderr)
        return 2

    target = HOME_CLAUDE / "CLAUDE.md"
    existing = target.read_text(encoding="utf-8") if target.exists() else ""
    mode = "DRY RUN — nothing written" if not args.apply else "APPLYING"
    print(f"install_user_scope: {mode}")
    print(f"  target: {HOME_CLAUDE}")
    print()

    if args.uninstall:
        updated = strip_block(existing)
        changed = updated != existing
        print(f"  {'remove' if changed else 'nothing to remove'}: managed block in {target}")
        print("  note: files under skills/, agents/ and commands/ are left in place;")
        print("        delete them by hand if you want them gone.")
        if args.apply and changed:
            target.write_text(updated, encoding="utf-8")
        return 0 if changed else 1

    updated = splice(existing, managed_block())
    verb = "update" if BEGIN in existing else ("create" if not existing.strip() else "append to")
    print(f"  {verb}: {target}  (managed block, {len(managed_block().splitlines())} lines)")
    if existing.strip() and BEGIN not in existing:
        print("           your existing content is kept above it, untouched.")

    actions = plan_copies(args.force)
    for src, dst, what in actions:
        print(f"  {what}: {dst}")

    if args.apply:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(updated, encoding="utf-8")
        for src, dst, what in actions:
            if what.startswith(("create", "overwrite")):
                dst.parent.mkdir(parents=True, exist_ok=True)
                if dst.exists():
                    shutil.copy2(dst, dst.with_suffix(dst.suffix + ".bak"))
                shutil.copy2(src, dst)

    print()
    print("  Reaches:      Claude Code sessions on this machine, any directory.")
    print("  Does NOT reach: claude.ai web conversations. They do not read ~/.claude/.")
    print("                  For those, paste prompts/base-operator.md into the")
    print("                  Project's custom instructions by hand.")
    if not args.apply:
        print()
        print("  Re-run with --apply to write.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
